### ISSUE TITLE
Customizer using g.hwnd instead of this._gui.hwnd

### ISSUE THREAD

**Issue by kczx3** [TheArkive/IronToolbar_AHK#1]
I'm assuming this was just overlooked while you were testing and partly due to not having the example usage commented out at the beginning.

This line should probably reference this._gui.hwnd instead of g.hwnd (g is defined as a global for your example usage).

https://github.com/TheArkive/IronToolbar_AHK/blob/9661f6bfe17a633840181fb12149699a6525a8b0/_Class_Toolbar.ahk#L765

**Comment by TheArkive** [comment]
yes indeed, that was an oversight.  Thanks.  I'll fix this soon.

**Comment by TheArkive** [comment]
Fixed.
